{% set name = "coconut" %}
{% set version = "3.1.0" %}
{% set build = 0 %}
# generate with `openssl sha256 coconut-<version>.tar.gz`
{% set sha256 = "e404e436e347d31e918d9bc870cc2e93a70b813739bd7b6c5d2353bdf3e6c777" %}
{% set pyparsing = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  entry_points:
    - coconut = coconut.main:main
    - coconut-run = coconut.main:main_run
  script: python -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pytest-remotedata
  run:
    - python
    - pyparsing {{ pyparsing }}
    - argparse  # [py<27]
    - psutil  # [py>=27]
    - futures  # [py<3]
    - backports.functools-lru-cache  # [py<3]
    - prompt_toolkit  # [py>=27]
    - pygments  # [py>=27]
    - typing_extensions  # [py>=37]

test:
  imports:
    - coconut
    - coconut.command
    - coconut.compiler
  commands:
    - coconut --version
    - coconut-run --version

about:
  home: http://coconut-lang.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Simple, elegant, Pythonic functional programming.'
  description: >
    Coconut is a functional programming language that compiles to Python. Since all valid Python is valid Coconut, using Coconut will only extend and enhance what you're already capable of in Python.
  doc_url: http://coconut.readthedocs.io/en/latest/DOCS.html
  dev_url: https://github.com/evhub/coconut

extra:
  recipe-maintainers:
    - evhub
