{% set name = "coconut" %}
{% set version = "2.1.1" %}
{% set build = 1 %}
# generate with `openssl sha256 coconut-<version>.tar.gz`
{% set sha256 = "38ce2c38c915e305e7c060a3e902d6ca8e504410182a0d4b50abe4df31aaebe3" %}
{% set pyparsing = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  entry_points:
    - coconut = coconut.main:main
    - coconut-run = coconut.main:main_run
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pytest-remotedata
  run:
    - python
    - pyparsing {{ pyparsing }}
    - argparse  # [py<27]
    - pygments  # [py>=27]
    - prompt_toolkit  # [py>=27]
    - futures  # [py<3]
    - backports.functools-lru-cache  # [py<3]
    - dataclasses  # [py==36]

test:
  imports:
    - coconut
    - coconut.command
    - coconut.compiler
  commands:
    - coconut --version
    - coconut-run --version

about:
  home: http://coconut-lang.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Simple, elegant, Pythonic functional programming.'
  description: >
    Coconut is a functional programming language that compiles
    to Python. Since all valid Python is valid Coconut, using
    Coconut will only extend and enhance what you're already
    capable of in Python.
  doc_url: http://coconut.readthedocs.io/en/latest/DOCS.html
  dev_url: https://github.com/evhub/coconut

extra:
  recipe-maintainers:
    - evhub
