# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mC/KnpsDQKd0A885hm6I/hS3S1X9ZvlHUAfp033qL9FXn4mdg6RiijGzJ81tCcDLvTwD4VP6HZ6w+P663i6nSiARKM5qLZqbNlumBQcrnNL1kBFSz9YzcbbVJk/SH8249GB2imqTDdAdHShgOSqr9QolDV6Of5aCaao1kosCfD8+lCHPP7/3iYpgeRsOMRE62iQO4OQ96xyv8ICPb7NjzHwUayzhrISzXgTiaiqz94RHfrblaRY6O4vMAq8PnGcZgRiBo1KJtYfnZ3TPjj5R99vD5El+EkUTKkieRHURGjA5qA2z2d2iq+/3y4ht9r0WmE/odHJ4kheN5lGqUR4qAsjxF1sU1jeeHt4+R2VeLulwQnbcCdLOsaxRSQXj6nvAxKPEzQYUkEsQ9wg8I0NZIrY0iAxktSAlPYUEiDMapVZgw9UqIL+VQFVElII0UYXzJyheVsAWTm9JyIO6FqIDEijNJ1ERmHAkaqD+f4rAhmH2NMchwyCz/7m+idIzlrXfygi945NBkIB2kldvXAQXUFf10ms8cwWkOUrn4Gyx9BtHgUz8vbIoHwSfnkRfCpIsRt5AdtXNkN4k0A5kO86MPEmtullwMyGaOB71GbeQol3VPCKGL7C6RYKNuBlhCjET4Jh3mdOXmtfQafOMoYbwOXKj/z9GzwQFTpUoYlLfV7s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
