# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PgKMsWqcoXJdXyoNWrPi3LbjLitQi3FKa2ajhcrPAQYlKclUvh3oaTvGNB+Rh0yypHDpRiXSU8OFltUGsKTmKZ2aBEn3RSu8AnmZU/+ZZUwPJeKwetUZ5AiAWAPg0MLX29jYurWtxb2OTXzssNE4wGZE4EA8nSp5Z6z+y3/HTFARF50ixjT7WIkuc8EnJVnyPilACEd8gwzuEjWhE2GZTVjxyN7yho5rvoUEUuU9Y8li2PHbb4Vf7kfkGmJMlBCJseUSQ/Dd61HQjv946CEvzcOYPfSyBBdLCkBxnmRfk16oJTP+uXjs4fzHxUcy7Vzj3V7ge9McJQzAe13P92Npl0knpunu208oFybSPgQwa1jsP7LyzWVibP03ZurzTXmh8gdwejA6/TuZVLYAqPHWM4UAgjp0i++BAVLoPg9eTEDhRaKK7cVxC0Ok3a8ACPbz2AY6uQy9i8yw7ZwbJfnd2lGn/+hXqYIlKyFl1vt7Z/ZXV8VWiTC+w/6I6o3PwiI7yCuQ6o6UekPTheOtj5wcp0In6ipUNg24+57Jsu4vK6dGuG6ejfms/xcPxt9CFGDr2c0J5pHkPY4L6pScMGb1Ynw2hgrnnI+Szi/Trodq2SiplSeUV2BerXwOM07IAVzbsfz7pSb6qcW8e1rL/rpdWSbBTGRs1stmwOf0rxHqWHk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
