travis:
  secure:
    BINSTAR_TOKEN: PgKMsWqcoXJdXyoNWrPi3LbjLitQi3FKa2ajhcrPAQYlKclUvh3oaTvGNB+Rh0yypHDpRiXSU8OFltUGsKTmKZ2aBEn3RSu8AnmZU/+ZZUwPJeKwetUZ5AiAWAPg0MLX29jYurWtxb2OTXzssNE4wGZE4EA8nSp5Z6z+y3/HTFARF50ixjT7WIkuc8EnJVnyPilACEd8gwzuEjWhE2GZTVjxyN7yho5rvoUEUuU9Y8li2PHbb4Vf7kfkGmJMlBCJseUSQ/Dd61HQjv946CEvzcOYPfSyBBdLCkBxnmRfk16oJTP+uXjs4fzHxUcy7Vzj3V7ge9McJQzAe13P92Npl0knpunu208oFybSPgQwa1jsP7LyzWVibP03ZurzTXmh8gdwejA6/TuZVLYAqPHWM4UAgjp0i++BAVLoPg9eTEDhRaKK7cVxC0Ok3a8ACPbz2AY6uQy9i8yw7ZwbJfnd2lGn/+hXqYIlKyFl1vt7Z/ZXV8VWiTC+w/6I6o3PwiI7yCuQ6o6UekPTheOtj5wcp0In6ipUNg24+57Jsu4vK6dGuG6ejfms/xcPxt9CFGDr2c0J5pHkPY4L6pScMGb1Ynw2hgrnnI+Szi/Trodq2SiplSeUV2BerXwOM07IAVzbsfz7pSb6qcW8e1rL/rpdWSbBTGRs1stmwOf0rxHqWHk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
