travis:
  secure:
    BINSTAR_TOKEN: jP5GlolGySRYQVPonJe2J1h4I0fhBtTHfhemmAe+/DU36HhqABTvjlS1+6RY8/y9vmqcM21t7vvpFh14pQAAAyLclqlkHD6+N87dtj1QxzRMEbXCFaQPJyU952uOHrqj09ZfwnYj/JzEbhUbe4xmqBXetz+arqvyvBzPiKgZFLU2XWG/ql781HeZHNqAfhQIu8MsaO09Klo16HqDghqLTpp2vAJUEhgdG3Q5labU877Ik6SrAMVQc3duGp4/NcnFYSXjaFjZ8alkq6Uck6QzoOv/brnCyiRzDoYC472yzQiytxpebvVR6gt2ofqoOdkVtLTmkqYFA2r6tOZTHnHIsGKjZwFjwZZ7rD4dGuYXqKjhBWtl2vt8SR96Pzcutdk36dXRAasLhNvJbfSF95QARbmP24jefa93e6sntpjHeYZt5qL3VnCPITSSxNP+V4FjkMjlrTd1x7wly3XtcujGXGIecn8Q3YjPgyiQNzAZ7k/kIHP4BAoMzJR85Tv/Jc9SXWwDnBvp8d6KE2n5BBbNu9MP2ApgkLCf/yTwZZ4twwq9tbLPzrSNMhrRZKAk6p5IhwsOJ70469rFi6TtAC43Nc2W7j6F0XBLQ0ZrBbbk90+25FYrt7JCs3+uqU+dW1Kps4CCLRuiZeAxT3bgSAIlkRUaNEgLQxNackY8J141w88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
