travis:
  secure:
    BINSTAR_TOKEN: k7bR4+Vn3X5zJ+y0oz3Ul8YvlyuJAAax34dW8cXV7Na3u2GSLfkcagN51H6aDl6rrw6qZ1/4Hhm8Ge44xpKB9N+sjm6FMvjXtJ2/anx4aOODcYpJXlYzX7hZC2uZbu2nbJCZs1L3sp2oywNDaIzIncNlU1ZvkY64wCPra/z87fjyPDBVXSe239CdGMO6tM6A5pqasRLPvCcyq5LEOrYO74L6DmFTQr3fJdSvya96n2JGrKixp+SoNkLpbcEJ+9PsxO8ukR2xcG27pwfSKWJjng6CU7qg41TJlnob9VCso55ZibULGf0yZaXAKwRqroAV92sNFXRUhr3wXOYiFLe3fUbiiELijl8CmiaiJfwkECGKTvsnOwE6YKFEm0ujQh5u5e6xBiDcDptTl6wPKth31iDE9Ysu6df+6tAoIFN2zMnON1tIKd0tO6OQ/FocIPrnIgt0VKuj993GUXRxM5HmrIZf+lTYnuj8WxKxHvYllEmDhYYiNHZpLn1TJ34dKq3tg3sZGepZmEUfhixMsX11YUE/aTqkeeL9cwhP5DfYctJcKokJl7svOIBFKrDCIxLsO+l+9kna5quPcoN1dDj1WiyghIEZWvn9rzw0Hnv8wi50UGp9zRlZueUVMVDMEVJ7HNHPXvPBIZZUvE2vG2AzOswlxrd6d2Adnht+G/mRNw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
