appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: EqmAs76MpTlBBALwmFRJjK/lHH6dL6b/egy8Qxj02MdJZhHrq3FwEUckAs8sxRbsIC4w0whvWkxv972KKMA3jgpmr9a8e1PxjUS6PTy80FraG5SvKkpIEdZrnY2CIRor8FYe8gnke/CMFCzOap9VRbj1AvxjjLZZPRV2NhNf5DcM+4Cro/CgE1HW94BucWZ/k4yzMFx0NWCpNqmaMCORPd84jDGszwIEYLL9AvIHgooiQQwcaPKsQ289cKylehyZ04khLiamxqinN5WcWEh8RBco7EJeTmuFBcUZCKE3sNllZzgzjUiDeUGK+ZAnDJ5xPrSmZcAqFMcgaL/ljW2Uwxw6Pf3xXgqwGnFIBeN35xoZDx2c2VmaoIkwCrHo0G/NBcRh1MVUgARSeYicQqsb+AlLDCHvO+0lLgdX4FdJHOJ8vyKfNrN3Pje9WntnvubfZ+6DciPFM5SQxXR+HAfVYDwJhQsnAQd0zhw+AGwJn4cePZ3ddSHLEqM6WFh7yrM7RPqe08lIlv46X//A4XwVQfbVeg/AxRqtP1KYOVoDV12oDMQATZOrB2xc4kdNNu/ehHx5m8J8ClQmVU/pG08zOckEg+tRmUI0r9EIew5yry9KpeAGzssR0yizSLBjqVZLYm+cV2sc948sOHQV2RtEMwaJfZ/xGlXBV4BBeklF5DU=}
provider:
  win: azure
conda_forge_output_validation: true
