travis:
  secure:
    BINSTAR_TOKEN: mC/KnpsDQKd0A885hm6I/hS3S1X9ZvlHUAfp033qL9FXn4mdg6RiijGzJ81tCcDLvTwD4VP6HZ6w+P663i6nSiARKM5qLZqbNlumBQcrnNL1kBFSz9YzcbbVJk/SH8249GB2imqTDdAdHShgOSqr9QolDV6Of5aCaao1kosCfD8+lCHPP7/3iYpgeRsOMRE62iQO4OQ96xyv8ICPb7NjzHwUayzhrISzXgTiaiqz94RHfrblaRY6O4vMAq8PnGcZgRiBo1KJtYfnZ3TPjj5R99vD5El+EkUTKkieRHURGjA5qA2z2d2iq+/3y4ht9r0WmE/odHJ4kheN5lGqUR4qAsjxF1sU1jeeHt4+R2VeLulwQnbcCdLOsaxRSQXj6nvAxKPEzQYUkEsQ9wg8I0NZIrY0iAxktSAlPYUEiDMapVZgw9UqIL+VQFVElII0UYXzJyheVsAWTm9JyIO6FqIDEijNJ1ERmHAkaqD+f4rAhmH2NMchwyCz/7m+idIzlrXfygi945NBkIB2kldvXAQXUFf10ms8cwWkOUrn4Gyx9BtHgUz8vbIoHwSfnkRfCpIsRt5AdtXNkN4k0A5kO86MPEmtullwMyGaOB71GbeQol3VPCKGL7C6RYKNuBlhCjET4Jh3mdOXmtfQafOMoYbwOXKj/z9GzwQFTpUoYlLfV7s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
