travis:
  secure:
    BINSTAR_TOKEN: dHneXyfwrJ+Vdpop5M1VSNMnuRYsg4mPipALHiLG/TmVvLg0kBgOWClWlOEKYHe/x0iW5bcpA4gUQsmsAUCEAqB7mPrRKEQ2uT13Lhe06T6KJLgJvQA2kN96JWzgQG9lO6A/ulM1lD8/YdatXcAK1kSmhZv4ONqQGmm9UFNH1Ylhq4wh2/HMIJCRCOT2nYsK4USioiZEamJqOI8zX44etaPoNKFPtDtUlIrvgmsZVhEwtArzYzOHIDlIwFglauW5Pn3r+mYtaKR0Rp4JRPxqBNeULkeN5k9KyEHEjK8tKOlnfHJ70XJYywecXhC5z6Bpbn69EjyM3s4qPAwVZKVWG1uFyvVSVgmWc7XSIhrgLeuuEAS51tWNw2MWl9xpJwQJaWYH7Qw1bUrZzOSoDKG4ye74CZ3+gqvvxRSDE6u2Ezf6Uu3gpgoV5mmaNLOIKx0XY1sbdkCFPJCIHhDnF4RgDpBJidFTVyqP23ntG4qtQSo8/tr0A/+riuETeYIjGwoZSFU652wB6yFFWOkXHhYP4DJEhjzXIukYS9NqYfm7UB4eTCHBFlHc5vSrdVmCikSxi/acdIlwqoadPxIqVSqu2KGF53uguw8/7KAg7RCoH9cuhSLT79vPEjgTOLFJV2WJvsJDiaJgz7+DmyhzVx2sgINiMtlpZwlVxfbbRm/DoKg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
